services:
  ## shared services

  mysql:
    image: mysql:9.4.0
    # ports:
    #   - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./migrations/base.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  redis:
    image: redis:8.2.2
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}
    user: root
    volumes:
      - redis-data:/data
    command:
      - sh
      - -c
      - |
        if [ -n "$${REDIS_PASS}" ]; then
          redis-server --requirepass "$${REDIS_PASS}"
        else
          redis-server
        fi

  ## application services

  bancho:
    # we also have a public image: osuakatsuki/bancho.py:latest
    image: bancho:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    tty: true
    init: true
    volumes:
      - .:/srv/root
      - data:/srv/root/.data
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - OSU_API_KEY=${OSU_API_KEY}
      - OSU_API_CLIENT_ID=${OSU_API_CLIENT_ID}
      - OSU_API_CLIENT_SECRET=${OSU_API_CLIENT_SECRET}
      - OSU_DAILY_API_KEY=${OSU_DAILY_API_KEY}
      - MIRROR_SEARCH_ENDPOINT=${MIRROR_SEARCH_ENDPOINT}
      - MIRROR_DOWNLOAD_ENDPOINT=${MIRROR_DOWNLOAD_ENDPOINT}
      - DOMAIN=${DOMAIN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - SEASONAL_BGS=${SEASONAL_BGS}
      - MENU_ICON_URL=${MENU_ICON_URL}
      - MENU_ONCLICK_URL=${MENU_ONCLICK_URL}
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - DATADOG_APP_KEY=${DATADOG_APP_KEY}
      - HCAPTCHA_SECRET_KEY=${HCAPTCHA_SECRET_KEY}
      - SMTP_SERVER_HOST=${SMTP_SERVER_HOST}
      - SMTP_SERVER_PORT=${SMTP_SERVER_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - DEBUG=${DEBUG}
      - REDIRECT_OSU_URLS=${REDIRECT_OSU_URLS}
      - PP_CACHED_ACCS=${PP_CACHED_ACCS}
      - DISALLOWED_NAMES=${DISALLOWED_NAMES}
      - DISALLOWED_PASSWORDS=${DISALLOWED_PASSWORDS}
      - DISALLOW_OLD_CLIENTS=${DISALLOW_OLD_CLIENTS}
      - DISALLOW_INGAME_REGISTRATION=${DISALLOW_INGAME_REGISTRATION}
      - DISALLOW_BEATMAP_SUBMISSION=${DISALLOW_BEATMAP_SUBMISSION}
      - DISCORD_URL=${DISCORD_URL}
      - DISCORD_AUDIT_LOG_WEBHOOK=${DISCORD_AUDIT_LOG_WEBHOOK}
      - DISCORD_BEATMAP_UPDATES_WEBHOOK=${DISCORD_BEATMAP_UPDATES_WEBHOOK}
      - AUTOMATICALLY_REPORT_PROBLEMS=${AUTOMATICALLY_REPORT_PROBLEMS}
      - LOG_WITH_COLORS=${LOG_WITH_COLORS}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - DEVELOPER_MODE=${DEVELOPER_MODE}
      - DB_USE_SSL=${DB_USE_SSL}

volumes:
  data:
  db-data:
  redis-data:
